name: benchmark
description: "A Flutter rebuild benchmark app comparing state management solutions."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management solutions
  provider: ^6.1.2
  flutter_bloc: ^8.1.4
  get: ^4.6.6
  flutter_riverpod: ^2.5.1
  drip_flutter:
    path: ../../packages/drip_flutter
  drip_core:
    path: ../../packages/drip_core
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
