name: drip_test
description: "Testing utilities for the DRIP framework."
version: 0.1.0-alpha
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  drip_core:
    path: ../drip_core

dev_dependencies:
  test: ^1.25.0
